### ISSUE TITLE
bancontact

### ISSUE THREAD

**Issue by Yakie996** [Razer2015/NordeaRootBypasser#1]
can you make such app for the belgian bancontact? https://play.google.com/store/apps/details?id=mobi.inthepocket.bcmc.bancontact

thank you

**Comment by Razer2015** [comment]
@Yakie996
I'll look into it.

**Comment by Yakie996** [comment]
thank you very much!
Regards

**Comment by Yakie996** [comment]
@Razer2015 do you think it will work?

**Comment by Razer2015** [comment]
@Yakie996 I've been looking into it. I thought I found it but it didn't work so there must be something else aswell :(. They have obfuscated the code quite nicely so that it's really hard to read it.

PS: Have you tried if rootcloak works?

**Comment by Yakie996** [comment]
oh that's regrettable... yes I tried and didn't work also disabled supersu in the app setting didn't work as wel .. also developer options has to be disabled...

**Comment by Razer2015** [comment]
Making these return 0 didn't work :(

![Image of Yaktocat](https://i.gyazo.com/56b2274917606de836e45107f6499be6.png)

**Comment by Yakie996** [comment]
I really hate it when they do this... let the user decide if they want to use it with root😔 same goes for android pay... they should make sort of a root safe zone for such apps

**Comment by Yakie996** [comment]
actually isn't that possible a partition to keep them safe from root?

**Comment by Razer2015** [comment]
I don't understand it either. You are allowed to be a system administrator in Windows when you log in to your bank, why not allow it with Android? If they can't make the application secure for users with root, then they shouldn't make it at all.

**Comment by Yakie996** [comment]
yes indeed + its a waste of their time and money to try block us to use it..

**Comment by Razer2015** [comment]
Yeap!

Anyways, I still have a few things I could try but not sure if they will work. I'll let you know if I can get this working.

**Comment by Yakie996** [comment]
okay great hope it works 😄

**Comment by Razer2015** [comment]
I was able to bypass the "USB Debugging enabled" one but still can't get around the main root checking :(. 

0x7f080109 is the resource id for the rooted text.
"The app could not be started because of a security error. Please check if developer settings are turned off and make sure your device is not rooted."

**Comment by Yakie996** [comment]
great work 😄 that's one problem out of the way 😋 do you have an idea what the problem could be?

**Comment by Razer2015** [comment]
There must be another check(s) somewhere in the obfuscated methods that I can't find :(. The problem is that you can't use string search because the strings are obfuscated as well.

**Comment by Yakie996** [comment]
so stupid that they do this 😔 so if you want to find it you should essentially have to read every line of code?

**Comment by Razer2015** [comment]
Well not necessarily. You would have to be able to recognize that it in fact is the code that checks it.

**Comment by Yakie996** [comment]
so it could be another app or service that's checking it?

**Comment by Yakie996** [comment]
there are also a lot of reports  of people that are saying they arent rooted etc but still are getting the warning

**Comment by Razer2015** [comment]
Found a EmulatorDetector o_O. How many fu****g checks do they have here :D.

**Comment by Yakie996** [comment]
omg haha enough to keep you buzzy :P

**Comment by Razer2015** [comment]
Well this looks good: RootedDetector

Hell yeah, it works :D. Atleast for my emulator.
![Image of root bypass](https://i.gyazo.com/034c11a107dbdf689c4c31cff40a947f.png)

**Comment by Razer2015** [comment]
S**t
![Image of unsuccess](https://i.gyazo.com/c71e0caf08e95f3f7892c11bd5caa24a.png)

**Comment by Yakie996** [comment]
what happened?

**Comment by Razer2015** [comment]
That's what came after entering a pin etc stuff. Idk how far I can actually even go with the app because I don't have account in that bank.

Something I found:
Lᵎ; -> AndroidIdDetector
Lﺫ; -> DebuggerDetector
LaUx; -> DeviceNameDetector
LӀ; -> EmulatorDetector
Lー; -> ImeiDetector
Lᵧ; -> IsScreenOnDetector
Lוּ; -> OperatorDetector
Lᔇ; -> PhoneNumberDetector
Lʟ; -> RootedDetector
Lsdhjrjstjnvftm; -> android.intent.action.SCREEN_ON
Lܙ; -> SimSerialNumberDetector
Lcon; -> LibSSLHash
Lї; -> SystemCoreHash
Lᵛ; -> HashOfJSC
Lᒢ; -> LibWebHash
Lᴶ; -> SignatureDetector
LΪ; -> MacAdressWifi
Lᵙ; -> AndClassLoader
Lʼ; -> fingerprint
Lˌ; -> WrongLockDetector

**Comment by Yakie996** [comment]
wauw improvement 😄 If you want, I can test it and give feedback. so many detectors 😳

**Comment by Yakie996** [comment]
oh great I didn't see the earlier post. did you adapt the code or are you working with xposed?

**Comment by Razer2015** [comment]
Here is the Xposed module I currently have.
https://drive.google.com/file/d/0B6emc59m4xTbQTVWN2YwcGRCUTA/view?usp=sharing

I'm inspecting the smali code -> edit it -> recompile -> install the modified apk.

**Comment by Yakie996** [comment]
okay great 😄

**Comment by Yakie996** [comment]
It worked for me! I added a card but after some time I get a toast message with 'developer options is enabled etc..' but the app doesn't stop working 😄 you did it 😁

**Comment by Razer2015** [comment]
Wuuut :D?

And yeah, the developer options pop up is just a pop up, it doesn't prevent you from using the app. Or well, there is two checks for that. The other one I am bypassing with the Xposed module but the one you are seeing I don't know how to code with Xposed. I can modify the apk to not have it though.

I wonder what is the "security issue" for me then. Country restriction?

**Comment by Yakie996** [comment]
yeah that could be it maybe you can mock your location to Belgium?

**Comment by Yakie996** [comment]
or maybe it can detect certain apps installed on your device? rootcloak  etc?

**Comment by Yakie996** [comment]
I don't have these apps installed

**Comment by Razer2015** [comment]
I should be bypassing them:

![Test](https://i.gyazo.com/e3e9b6a0a8d97005f2d92e5a4ba0db63.png)

**Comment by Yakie996** [comment]
strange but its working fine for me 😂 this app is some strange alien 😋 was it actually difficult to do?

**Comment by Razer2015** [comment]
Well the hardest I've come across yet. But I ain't no pro :).

**Comment by Yakie996** [comment]
haha Belgium unnecessary security 😏 I would love to do this too 😃

**Comment by Yakie996** [comment]
how come people didn't crack android pay?

**Comment by Razer2015** [comment]
Made by google. Their OS so they have access/knowledge to make it even harder than what other developers can.

**Comment by Yakie996** [comment]
oh yeah right.. btw you're pro enough to crack this thing 😄 👍🏼

**Comment by Razer2015** [comment]
Made own repository for this:
https://github.com/Razer2015/BancontactRootBypasser/issues/1
