### ISSUE TITLE
Stopped working after the latest update =(

### ISSUE THREAD

**Issue by AnIK2k17** [Razer2015/NordeaRootBypasser#6]

**Comment by kyrasantae** [comment]
Yep, it appears that Codes 1.5.2 has been released.

**Comment by Razer2015** [comment]
I'll look into it.

**Comment by Razer2015** [comment]
Should work with this: https://github.com/Razer2015/NordeaRootBypasser/releases/tag/v1.3

Edit: Xposed Repo updated as well.

**Comment by kyrasantae** [comment]
I had to do the little dance with removing and reinstalling both the code app and the module and rebooting, but it's working for me now. Thanks!

**Comment by AnIK2k17** [comment]
Yes, it's working again, thank you very much!
Any chance you can help also with the Nordea Pay app?
